export enum ENUM_DELIVERY_MAN_DUTY_STATUS {
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE',
  IN_TRANSIT = 'IN_TRANSIT',
}

export enum ENUM_DELIVERY_MAN_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TEMPORARY_BLOCKED = 'TEMPORARY_BLOCKED',
}
