export enum ENUM_FEEDBACK_TAG {
  UI = 'UI',
  BUG = 'BUG',
  FEATURE = 'FEATURE',
  PERFORMANCE = 'PERFORMANCE',
  DOCUMENTATION = 'DOCUMENTATION',
  OTHER = 'OTHER',
}

export enum ENUM_FEEDBACK_STATUS {
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}
