export enum ENUM_TRANSACTION_TYPE {
  DELIVERY_EARNING = 'DELIVERY_EARNING',
  ORDER_PAYMENT = 'ORDER_PAYMENT',
  DELIVERY_MAN_PAYMENT = 'DELIVERY_MAN_PAYMENT',
  REFUND = 'REFUND',
  OTHER = 'OTHER',
}

export enum ENUM_TRANSACTION_STATUS {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
