// Generated by `pnpm cf-typegen` and extended manually. Do not remove manual additions.
/// <reference types="@cloudflare/vitest-pool-workers/types" />
interface CloudflareBindings {
  DB: D1Database;
  MODE: string;
  JWT_SECRET: string;
  JWT_EXPIRES_IN: string;
  JWT_REFRESH_EXPIRES_IN: string;
  OTP_SECRET: string;
  OTP_EXPIRY_SEC: string;
  ROOT_USER_EMAIL: string;
  MAIL_FROM: string;
  MAIL_API_KEY?: string;
  WEB_ORDER_TRACKING_BASE_URL: string;
  SLACK_ORDER_CHANNEL_ID: string;
  SLACK_WEBHOOK_URL: string;
  FCM_PROJECT_ID: string;
  FCM_SERVICE_ACCOUNT?: string;
  SMS_API_KEY?: string;
  SSL_STORE_ID: string;
  SSL_STORE_PASSWORD: string;
  ORDER_QUEUE: Queue;
  ORDER_EVENTS_QUEUE: Queue;
  STORAGE: R2Bucket;
}

declare namespace Cloudflare {
  interface Env extends CloudflareBindings {
    TEST_MIGRATIONS: string;
  }
}
